### ISSUE TITLE
[feat] CI/CD 구축하기

### ISSUE THREAD

**Issue by jiho313** [jiho313/anniehands#28]
## 🚀 구현 사항
- GitHub Action과 AWS 서비스로 CI/CD(지속적 통합/지속적 배포) 구축하기

## 📋 TODO
- [x] S3 버킷 생성 
- [x] CodeDeploy 생성
- [x] GitHub Action Workflow.yml 정의하기
- [x] 배포  스크립트 작성
- [x] AppSpec.yml 작성
