### ISSUE TITLE
[feat] 카테고리 별 상품 리스트 출력 구현

### ISSUE THREAD

**Issue by jiho313** [jiho313/anniehands#36]
## 🚀 구현 사항
- 각 카테고리 별로 상품 리스트 출력 구현한다.
  - 상위 카테고리로 강아지와 고양이가 있다.
  - 하위 카테고리로 각 주식, 간식, 건강보조제, 패션이 있다.
  - 정렬 순서로 신상품, 낮은 가격, 높은 가격, 인기 상품이 있다.

## 📋 TODO
- [x] 상위 카테고리 기준 출력
- [x] 하위 카테고리 기준 출력
- [x] 정렬 순서 구현

## 🔍 참고 사항
- 인기 상품은 총 주문 수량을 기준으로 하기 때문에 이 정렬법은 추후에 구현할 예정이다.
