### ISSUE TITLE
[feat] 홈페이지 회원가입 기능구현 

### ISSUE THREAD

**Issue by jiho313** [jiho313/anniehands#9]
## 🚀 구현 사항
- **AnnieHands** 홈페이지에서의 회원가입 기능을 구현한다.

## 📋 TODO
- [ ] 홈페이지내에서 회원가입을 하고 DB에 고객 데이터를 저장한다.
- [ ] 회원 비밀번호는 암호화되어야 한다.
- [ ] 회원은 ROLE은 USER와 ADMIN이다.
- [ ] 회원의 ROLE은 `ENUM`으로 관리된다.
- [ ] 우편번호 검색 api 사용
- [ ] 핸드폰 인증 기능 구현

## 🔍 참고 사항
- 추후 OAuth를 이용한 소셜 로그인을 구현할 예정
